### ISSUE TITLE
Should GetSelection panic or return nil?

### ISSUE THREAD

**Issue by AlexVanin** [nspcc-dev/netmap#17]
`GetSelection` function returns `*Bucket`, but in case of internal errors it can panic. For example if there is a `Select` rule bigger than available `*Bucket`

```go
func TestBucket_RuntimeError(t *testing.T) {
	g := NewGomegaWithT(t)
	buckets := []bucket{
		{"/Location:Europe/Country:Spain/City:Madrid", []uint32{17, 18}},
	}
	root, err := newRoot(buckets...)
	g.Expect(err).NotTo(HaveOccurred())

	ss := []Select{
		{Key: NodesBucket, Count: 3}, // available only two
	}

	r := root.GetSelection(ss, defaultPivot)
	g.Expect(r).NotTo(BeNil())
}
```

This code leads to panic
```
=== RUN   TestBucket_RuntimeError
--- FAIL: TestBucket_RuntimeError (0.00s)
panic: runtime error: slice bounds out of range [recovered]
	panic: runtime error: slice bounds out of range
```

In our code we avoid this case by calling `GetMaxSelection` in advance. This function returns error if something goes wrong. But in general I don't know whether is it correct behaviour for `GetSelection` function to panic.

**Comment by im-kulikov** [comment]
@AlexVanin it should not panic, it's a bug

**Comment by AlexVanin** [comment]
cc: @fyrchik

**Comment by im-kulikov** [comment]
@AlexVanin @fyrchik I can fix it, if there is no objection
