### ISSUE TITLE
Inconsisting selection behavior

### ISSUE THREAD

**Issue by AlexVanin** [nspcc-dev/netmap#6]
## Description
There is an inconsistency in `GetSelection` function. The result is depended on order of added buckets, even if buckets are the same. This is incorrect behavior.

## Proposal
`GetSelection` function took `*rand.Rand` as a parameter. This object used for predictable randomization: same objects will have same seed number, therefore same output. This is true only if both objects have slice of bucket with the same order. 

I see two solutions:
1. Sort all buckets before every random choice
2. Use `HRW` instead of randomization

I prefer second solution, because there is no guarantee that same seed number will lead to the same choices on different machines. Traversal operations must be completely predictable, so `HRW` is great for that purpose.

## Test

```go
func TestBucket_ShuffledSelection(t *testing.T) {
	var (
		err       error
		exp, root Bucket
		r, expr  *Bucket
		buckets   []bucket
		shuffledBuckets   []bucket
		ss        []Select
	)
	g := NewGomegaWithT(t)

	buckets = []bucket{
		{"/Location:Asia/Country:Korea", []int32{1, 3}},
		{"/Location:Asia/Country:China", []int32{2}},
		{"/Location:Europe/Country:Germany/City:Hamburg", []int32{25}},
		{"/Location:Europe/Country:Germany/City:Bremen", []int32{27, 29}},
		{"/Location:Europe/Country:Spain/City:Madrid", []int32{17, 18}},
		{"/Location:Europe/Country:Spain/City:Barcelona", []int32{26, 30}},
		{"/Location:NorthAmerica/Country:USA/City:NewYork", []int32{19, 20}},
	}

	ss = []Select{
		{Key: "City", Count: 3},
		{Key: NodesBucket, Count:1},
	}

	shuffledBuckets = make([]bucket, len(buckets))
	copy(shuffledBuckets, buckets)
	// if you comment shuffle lines, test will be passed
	rand.Shuffle(len(shuffledBuckets), func(i, j int) {
		shuffledBuckets[i] ,shuffledBuckets[j] = shuffledBuckets[j], shuffledBuckets[i]
	})

	exp, err = newRoot(buckets...)
	g.Expect(err).NotTo(HaveOccurred())

	root, err = newRoot(shuffledBuckets...)
	g.Expect(err).NotTo(HaveOccurred())

	random := rand.New(rand.NewSource(1))
	expr = exp.GetSelection(ss, random)
	g.Expect(expr).NotTo(BeNil())

	random = rand.New(rand.NewSource(1))
	r = root.GetSelection(ss, random)
	g.Expect(r).NotTo(BeNil())

	g.Expect(r.nodes).To(Equal(expr.nodes))
}
```

**Comment by im-kulikov** [comment]
fixed by [nspcc-dev/hrw](https://github.com/nspcc-dev/hrw) + https://github.com/nspcc-dev/netmap/pull/7
